services:
  - type: static_site
    name: luxetime-frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: "https://luxetime-e-commerce.onrender.com"
